package se.yrgo.dataaccess;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;

import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;

public class CustomerDaoJdbcTemplateImpl implements CustomerDao {
    private static final String DELETE_SQL = "DELETE FROM CUSTOMER WHERE CUSTOMER_ID=?";
    private static final String UPDATE_SQL = "UPDATE CUSTOMER SET COMPANY_NAME=?, EMAIL=?, TELEPHONE=?, NOTES=? WHERE CUSTOMER_ID=?";
    private static final String INSERT_SQL = "INSERT INTO CUSTOMER (CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES) VALUES (?,?,?,?,?)";

    private JdbcTemplate template;

    public CustomerDaoJdbcTemplateImpl(JdbcTemplate template) {
        this.template = template;
        this.template.update("DROP TABLE CALLS IF EXISTS");
        this.template.update("DROP TABLE CUSTOMER IF EXISTS");
        createTables();
    }

    private void createTables() {
        this.template.update(
                "CREATE TABLE CUSTOMER (CUSTOMER_ID VARCHAR(20) primary key, COMPANY_NAME VARCHAR(255), EMAIL VARCHAR(255), TELEPHONE VARCHAR(20), NOTES VARCHAR(255))");
        this.template.update(
                "CREATE TABLE CALLS (CALL_ID integer generated by default as identity (start with 1), CUSTOMER_ID VARCHAR(20), TIME_AND_DATE DATE, NOTES VARCHAR(255), foreign key (CUSTOMER_ID) references Customer(CUSTOMER_ID))");
    }

    @Override
    public void create(Customer customer) {
        template.update(INSERT_SQL,
                customer.getCustomerId(),
                customer.getCompanyName(),
                customer.getEmail(),
                customer.getTelephone(),
                customer.getNotes());
    }

    @Override
    public Customer getById(String customerId) throws RecordNotFoundException {
        List<Customer> customers = template.query("Select * from Customer where CUSTOMER_ID=?", new CustomerMapper(),
                customerId);

        return customers.get(0);
    }

    @Override
    public List<Customer> getByName(String name) {
        return template.query("Select * from Customer where COMPANY_NAME=?", new CustomerMapper(),
                name);
    }

    @Override
    public void update(Customer customerToUpdate) throws RecordNotFoundException {
        template.update(UPDATE_SQL,
                customerToUpdate.getCompanyName(),
                customerToUpdate.getEmail(),
                customerToUpdate.getTelephone(),
                customerToUpdate.getNotes(),
                customerToUpdate.getCustomerId());
    }

    @Override
    public void delete(Customer oldCustomer) throws RecordNotFoundException {
        template.update(DELETE_SQL, oldCustomer.getCustomerId());
    }

    @Override
    public List<Customer> getAllCustomers() {
        return template.query("Select * from Customer", new CustomerMapper());
    }

    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        List<Customer> customers = template.query("Select * from Customer where CUSTOMER_ID=?", new CustomerMapper(),
                customerId);
        List<Call> calls = template.query("Select * from Calls where CUSTOMER_ID=?", new CallMapper(), customerId);
        customers.get(0).setCalls(calls);

        return customers.get(0);
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        template.update(
                "INSERT INTO CALLS (CUSTOMER_ID, TIME_AND_DATE, NOTES) VALUES (?,?,?)",
                customerId,
                newCall.getTimeAndDate(),
                newCall.getNotes());
    }

    class CustomerMapper implements RowMapper<Customer> {
        @Override
        public Customer mapRow(ResultSet rs, int rowNum) throws SQLException {
            String customerId = rs.getString("CUSTOMER_ID");
            String companyName = rs.getString("COMPANY_NAME");
            String email = rs.getString("EMAIL");
            String telephone = rs.getString("TELEPHONE");
            String notes = rs.getString("NOTES");

            Customer customer = new Customer(customerId, companyName, email, telephone, notes);
            return customer;
        }
    }

    class CallMapper implements RowMapper<Call> {
        @Override
        public Call mapRow(ResultSet rs, int rowNum) throws SQLException {
            Date timeAndDate = rs.getDate("TIME_AND_DATE");
            String notes = rs.getString("NOTES");

            Call call = new Call(notes, timeAndDate);
            return call;
        }
    }
}